package health

import "github.com/prometheus/client_golang/prometheus"

// Metrics holds all Prometheus instruments for the rng-service.
// Register with NewMetrics; update via the provided methods.
type Metrics struct {
	// NIST self-test p-values (labels: test="Frequency|Runs|BlockFrequency")
	NISTTestPValue *prometheus.GaugeVec

	// Total bytes generated by the CSPRNG (label: tenant)
	OutputsTotal *prometheus.CounterVec

	// Total re-seeds (label: reason="startup|scheduled|event")
	ReseedsTotal *prometheus.CounterVec

	// 1.0 if binary hash matches startup hash; 0.0 on tamper detection
	BinaryHashMatches prometheus.Gauge

	// Unix timestamp of the last NIST self-test run
	SelfTestLastRunTimestamp prometheus.Gauge
}

// NewMetrics registers all instruments with the provided Prometheus registerer
// and returns the initialized Metrics struct.
func NewMetrics(reg prometheus.Registerer) *Metrics {
	m := &Metrics{
		NISTTestPValue: prometheus.NewGaugeVec(prometheus.GaugeOpts{
			Name: "rng_nist_test_p_value",
			Help: "NIST SP 800-22 test p-value. Acceptable range: (0.01, 0.99).",
		}, []string{"test"}),

		OutputsTotal: prometheus.NewCounterVec(prometheus.CounterOpts{
			Name: "rng_outputs_total",
			Help: "Total bytes generated by the CSPRNG, by tenant.",
		}, []string{"tenant"}),

		ReseedsTotal: prometheus.NewCounterVec(prometheus.CounterOpts{
			Name: "rng_reseeds_total",
			Help: "Total CSPRNG re-seeds by reason (startup|scheduled|event).",
		}, []string{"reason"}),

		BinaryHashMatches: prometheus.NewGauge(prometheus.GaugeOpts{
			Name: "rng_binary_hash_matches",
			Help: "1.0 if binary hash matches startup hash; 0.0 indicates tamper detection.",
		}),

		SelfTestLastRunTimestamp: prometheus.NewGauge(prometheus.GaugeOpts{
			Name: "rng_selftest_last_run_timestamp_seconds",
			Help: "Unix timestamp of the last NIST self-test run.",
		}),
	}

	reg.MustRegister(
		m.NISTTestPValue,
		m.OutputsTotal,
		m.ReseedsTotal,
		m.BinaryHashMatches,
		m.SelfTestLastRunTimestamp,
	)

	// Initialize binary hash gauge to 1.0 (healthy at startup).
	m.BinaryHashMatches.Set(1.0)

	return m
}

// UpdateNIST sets the p-value for a given test name.
func (m *Metrics) UpdateNIST(results []TestResult) {
	for _, r := range results {
		m.NISTTestPValue.WithLabelValues(r.Name).Set(r.PValue)
	}
}

// RecordOutput increments the output byte counter for a tenant.
func (m *Metrics) RecordOutput(tenantID string, bytes uint64) {
	m.OutputsTotal.WithLabelValues(tenantID).Add(float64(bytes))
}

// RecordReseed increments the reseed counter for a given reason.
func (m *Metrics) RecordReseed(reason string) {
	m.ReseedsTotal.WithLabelValues(reason).Inc()
}

// SetTamperDetected sets BinaryHashMatches to 0.0 (tamper detected) or 1.0 (ok).
func (m *Metrics) SetTamperDetected(detected bool) {
	if detected {
		m.BinaryHashMatches.Set(0.0)
	} else {
		m.BinaryHashMatches.Set(1.0)
	}
}
